config/routes.rb
Rails.application.routes.draw do
  get 'bookmakers/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'homes#top'
  post 'bookmakers' => 'bookmakers#create'
  get 'bookmakers' => 'bookmakers#index'
  get 'bookmakers/:id' => 'bookmakers#show', as: 'bookmaker'
  get 'bookmakers/:id/edit' => 'bookmakers#edit', as: 'edit_bookmaker'
  patch 'bookmakers/:id' => 'bookmakers#update', as: 'update_bookmaker'
  delete 'bookmakers/:id' => 'bookmakers#destroy', as: 'destroy_bookmaker'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/bookmakers_controller.rb
class BookmakersController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "SUCCESS"
      redirect_to bookmaker_path(@book.id)
    else
      @books = Book.all
      @books = Book.all.order(created_at: :desc)
      # @book=Book.new
      render :index
    end
  end

  def index
    @books = Book.all
    @books = Book.all.order(created_at: :desc)
  end

  def show
    @book = Book.find(params[:id])
  end
  def edit
    @book = Book.find(params[:id])
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to edit_bookmaker_path
    else
      render 'bookmakers/edit'
    end
  end
  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed"
    redirect_to bookmakers_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmakers_helper.rb
module BookmakersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/bookmakers/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url:"/bookmakers/#{@book.id}", local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>
<% end %>
<%= link_to "Show", bookmaker_path(@book.id) %>
<%= link_to "Back", bookmakers_path %>

app/views/bookmakers/index.html.erb
<h1><b>Books</b></h1>

<table>
  <thead>
    <th><b>Title</b></th>
    <th><b>Body</b></th>
    <th colspan="3"></th>
  </thead>

  <tbody>
    <%  @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to 'Show', bookmaker_path(book.id) %></td>
      <td><%= link_to 'Edit', edit_bookmaker_path(book.id) %></td>
      <td><%= link_to 'Destroy', destroy_bookmaker_path(book.id), method: :delete, "data-confirm" =>"Are you sure?" %></td>
   </tr>
   <% end %>
  </tbody>
</table>


<h2><b>New book</b></h2>
<div class= field_with_errors>
    <% if @book && @book.errors.any? %>
    <%= @book.errors.count %>error(s) occoured.
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
</div>

<%= form_with model: Book.new, url:'/bookmakers', local:true do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

app/views/bookmakers/new.html.erb
<h1>New Book</h1>
<!-- form_with部分 -->
<%= form_with model: @book, url:'/bookmakers', local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'create new book' %>
<% end %>

app/views/bookmakers/show.html.erb
<div class="container spa1">
    <p><b>Title:</b><p>
    <p><%= @book.title %></p>
</div>
<div class="container spa1">
    <p><b>Body:</b></p>
    <p><%= @book.body %></p>
</div>
<div class="container spa2">
    <p><%= link_to "Edit", edit_bookmaker_path(@book.id) %></p>
    <p>|</p>
    <p><%= link_to "Back", bookmakers_path %></p>
</div>

app/views/homes/top.html.erb
<h1><b>ようこそ Bookers へ!</b></h1>
<div class="spa1">
  <p><b>Bookers</b>では、様々な書籍に関するあなたの意見や<br>印象を共有し交換することができます。</p>
  <span>
    <%= link_to 'start', "/bookmakers" %>
  </span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersKadai</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <p id="notice"><%= notice %></p>
   <p id="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>